CREATE TABLE PURCHASE(
ORDERID VARCHAR(25) PRIMARY KEY
);

-- VARCHAR2 is not a valid data type in MySQL

CREATE TABLE USERS (USERNAME VARCHAR (10) PRIMARY KEY,
PASSWD VARCHAR (16) NOT NULL,
EMAIL VARCHAR (30) NOT NULL,
FNAME VARCHAR (25) NOT NULL,
LNAME VARCHAR (25) NOT NULL, 
SIGNUP_DATE DATE,
USER_KEY VARCHAR (25) NOT NULL
); 

--DATE DEFAULT SYSDATE is not acceptable format for MySQL, just use DATE

CREATE TABLE MOVIES (
TITLE VARCHAR2 (25) PRIMARY KEY,
MOVIE_KEY VARCHAR2(25) NOT NULL,
GENRE VARCHAR2 (20) NOT NULL, 
LENGHT VARCHAR2 (300) NOT NULL
);

ALTER TABLE USERS ADD ORDERID VARCHAR (25) NOT NULL; 

ALTER TABLE USERS ADD CONSTRAINT FOREIGN KEY (ORDERID) 
REFERENCES PURCHASE (ORDERID);

--Updated foreign key to USERS table

ALTER TABLE MOVIES ADD PRICE VARCHAR (6) NOT NULL;

ALTER TABLE PURCHASE ADD USERNAME VARCHAR(10) NOT NULL;
ALTER TABLE PURCHASE ADD PRICE VARCHAR(6) NOT NULL;

ALTER TABLE PURCHASE ADD CONSTRAINT FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);

--Used phpMyAdmin to input values into table to test php code 
