CREATE TABLE PURCHASE(
ORDERID VARCHAR(25) PRIMARY KEY
);

-- VARCHAR2 is not a valid data type in MySQL

CREATE TABLE USERS (USERNAME VARCHAR (10) PRIMARY KEY,
PASSWD VARCHAR (16) NOT NULL,
EMAIL VARCHAR (30) NOT NULL,
FNAME VARCHAR (25) NOT NULL,
LNAME VARCHAR (25) NOT NULL, 
SIGNUP_DATE DATE,
USER_KEY VARCHAR (25) NOT NULL
); 

--DATE DEFAULT SYSDATE is not acceptable format for MySQL, just use DATE

CREATE TABLE MOVIES (
TITLE VARCHAR2 (25) PRIMARY KEY,
MOVIE_KEY VARCHAR2(25) NOT NULL,
GENRE VARCHAR2 (20) NOT NULL, 
LENGHT VARCHAR2 (300) NOT NULL
);

